In [2]:
import numpy as np

In [4]:
a = ([1,2,3],[4,5,6],[7,8,9])
print(type(a))

<class 'tuple'>


In [8]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = [[1,2,3],[4,5,6],[7,8,9]]
display(a[0])
a[0]
b[0]

array([1, 2, 3])

[1, 2, 3]

In [9]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [10]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [12]:
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [13]:
np.empty(3,order='F')

array([ 1.02437498e-311,  1.02438577e-311, -0.00000000e+000])

In [14]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [17]:
cth = np.arange(5,10,2)
cth

array([5, 7, 9])

In [18]:
#appending 2 or more array
np.append(cth, [1,2,3])

array([5, 7, 9, 1, 2, 3])

In [19]:
#deleting element of array by index 
np.delete(cth,1)

array([5, 9])

In [22]:
cth = np.arange(1,2,10)
np.attend(cth, [1,2,10])
cth

AttributeError: module 'numpy' has no attribute 'attend'

In [25]:
np.array = ([5,6,7])
np.append(cth, [1,2])

np.delete(cth,0)

np.sort(cth)

array([1])

In [65]:
def array_example (np.array)
    [   [0,1,2,3],
        [4,5,6,7]],
    [   [0,1,2,3],
        [4,5,6,7]],
    [   [0,1,2,3],
        [4,5,6,7]],

print(array_example)

SyntaxError: invalid syntax (4034437551.py, line 1)

In [37]:
a = np.arange(16)
b = a.reshape 

In [38]:
display(a)
a2 = a[np.newaxis]
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [40]:
display(a2)
a3 = a2[np.newaxis]
a3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]]])

In [43]:
display(a3)
row_vector = a[np.newaxis, :]
row_vector

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]]])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [45]:
row_vector = a[:, np.newaxis]
row_vector

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [46]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [52]:
a = np.arange(5)
display(a)
display(a.shape)
b = np.expand_dims(a, axis = 1)
b

array([0, 1, 2, 3, 4])

(5,)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [51]:
display(b.shape)

(5, 1)

In [54]:
b = np.expand_dims(a, axis = 0)
b

array([[0, 1, 2, 3, 4]])

In [55]:
a

array([0, 1, 2, 3, 4])

In [56]:
a[0]

0

In [57]:
a[2]

2

In [60]:
#untuk ambil nilai dr depan
print(a[:3])
#untuk ambil nilai dr blkg
print(a[::-1])
#untuk ambil nilai paling blkg
print(a[-1])
print(a[-2:])

[0 1 2]
[4 3 2 1 0]
4
[3 4]


In [61]:
five

NameError: name 'array_example' is not defined

In [66]:
a = np.arange(1,11)
b = a[3:8]
b

array([4, 5, 6, 7, 8])

In [70]:
a1 = np.array([[0,1,],[4,5,]])
a2 = np.array([[2,3,],[6,7,]])

TypeError: 'list' object is not callable

In [71]:
display(a)
a2 = a[np.newaxis]
a4 = np.vstack((a2,a2))
a4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [72]:
np.hsplit(a4,2)

[array([[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10],
        [ 6,  7,  8,  9, 10]])]

In [73]:
np.hsplit(a4,5)

[array([[1, 2],
        [1, 2]]),
 array([[3, 4],
        [3, 4]]),
 array([[5, 6],
        [5, 6]]),
 array([[7, 8],
        [7, 8]]),
 array([[ 9, 10],
        [ 9, 10]])]

In [78]:
a 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
b = a.view()
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
b = a.copy() #copy dan view itu sama 
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [85]:
a = np.arange(3)
b = np.arange(4,7)
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[0 1 2]
[4 5 6]
[4 6 8]
[-4 -4 -4]
[ 0  5 12]
[0.         0.2        0.33333333]


In [86]:
b.sum()

15

In [88]:
a3

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]]])

In [89]:
a3.sum()

120

In [92]:
print(a.max())
print(a.min())
print(a.sum())
print(a.std())

2
0
3
0.816496580927726


In [94]:
a1 = np.array([[0,1],[4,5],[7,8]])
print(a1)
a2 = np.array([

NameError: name 'a1' is not defined